export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const FETCH_FOLLOWING = 'FETCH_FOLLOWING';
export const FETCH_YOURSELF = 'FETCH_YOURSELF';
export const FOLLOW_SOMEONE = 'FOLLOW_SOMEONE';
