// 引入 rnplus
import 'rnplus';
import 'rnplus-plugin-webx';

import './config';

// 引入页面
import './view/Base';
// router
import './view/PageA';
import './view/PageB';
// scene
import './view/Scene';
import './view/SceneBlank';
import './view/SceneAndroidBack';
// popup
import './view/Popup';
// bridge
import './view/Bridge';
// webx
import './view/WebX';
// redux
import './view/ReduxList';
import './view/ReduxDetail';
// rnx-ui
import './view/RNXUI';
import './view/RNXUIAccordion';
import './view/RNXUICalendar';
import './view/RNXUICarousel';
import './view/RNXUIDialog';
import './view/RNXUIDropDown';
import './view/RNXUINavBar';
import './view/RNXUINumber';
import './view/RNXUIPopover';
import './view/RNXUIScrollView';
import './view/RNXUIToolTip';
// 字体
import './view/IconFont';
// 图片
import './view/ImageDemo';
