// 引入 rnplus
import 'rnplus';

import './config';

// 引入页面
import './view/Base';
// router
import './view/PageA';
import './view/PageB';
// scene
import './view/Scene';
import './view/SceneBlank';
import './view/SceneAndroidBack';
// navBar
import './view/NavBar';
// popup
import './view/Popup';
// bridge
import './view/Bridge';
// webx
import './view/WebX';
// redux
import './view/ReduxList';
import './view/ReduxDetail';
// components
import './view/Components';
import './view/CompAccordion';
import './view/CompCalendar';
import './view/CompCarousel';
import './view/CompDialog';
import './view/CompDropDown';
import './view/CompNumber';
import './view/CompPopover';
import './view/CompToolTip';
// 字体
import './view/IconFont';
// 图片
import './view/ImageDemo';
